/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropiedadesRouteImport } from './routes/propiedades'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesSlugRouteImport } from './routes/propiedades.$slug'
import { Route as AdminPropiedadesRouteImport } from './routes/admin/propiedades'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminPropiedadesNuevaRouteImport } from './routes/admin/propiedades.nueva'
import { Route as AdminLeadsIdRouteImport } from './routes/admin/leads.$id'
import { Route as AdminPropiedadesIdEditarRouteImport } from './routes/admin/propiedades.$id.editar'

const PropiedadesRoute = PropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesSlugRoute = PropiedadesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PropiedadesRoute,
} as any)
const AdminPropiedadesRoute = AdminPropiedadesRouteImport.update({
  id: '/propiedades',
  path: '/propiedades',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropiedadesNuevaRoute = AdminPropiedadesNuevaRouteImport.update({
  id: '/nueva',
  path: '/nueva',
  getParentRoute: () => AdminPropiedadesRoute,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminLeadsRoute,
} as any)
const AdminPropiedadesIdEditarRoute =
  AdminPropiedadesIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AdminPropiedadesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/propiedades': typeof AdminPropiedadesRouteWithChildren
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/propiedades': typeof AdminPropiedadesRouteWithChildren
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/propiedades': typeof PropiedadesRouteWithChildren
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/leads': typeof AdminLeadsRouteWithChildren
  '/admin/propiedades': typeof AdminPropiedadesRouteWithChildren
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/propiedades'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/propiedades'
    | '/propiedades/$slug'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/propiedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/propiedades'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/propiedades'
    | '/propiedades/$slug'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/propiedades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacto'
    | '/login'
    | '/nosotros'
    | '/propiedades'
    | '/admin/dashboard'
    | '/admin/leads'
    | '/admin/propiedades'
    | '/propiedades/$slug'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/propiedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  PropiedadesRoute: typeof PropiedadesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/propiedades': {
      id: '/propiedades'
      path: '/propiedades'
      fullPath: '/propiedades'
      preLoaderRoute: typeof PropiedadesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$slug': {
      id: '/propiedades/$slug'
      path: '/$slug'
      fullPath: '/propiedades/$slug'
      preLoaderRoute: typeof PropiedadesSlugRouteImport
      parentRoute: typeof PropiedadesRoute
    }
    '/admin/propiedades': {
      id: '/admin/propiedades'
      path: '/propiedades'
      fullPath: '/admin/propiedades'
      preLoaderRoute: typeof AdminPropiedadesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propiedades/nueva': {
      id: '/admin/propiedades/nueva'
      path: '/nueva'
      fullPath: '/admin/propiedades/nueva'
      preLoaderRoute: typeof AdminPropiedadesNuevaRouteImport
      parentRoute: typeof AdminPropiedadesRoute
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof AdminLeadsRoute
    }
    '/admin/propiedades/$id/editar': {
      id: '/admin/propiedades/$id/editar'
      path: '/$id/editar'
      fullPath: '/admin/propiedades/$id/editar'
      preLoaderRoute: typeof AdminPropiedadesIdEditarRouteImport
      parentRoute: typeof AdminPropiedadesRoute
    }
  }
}

interface AdminLeadsRouteChildren {
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
}

const AdminLeadsRouteChildren: AdminLeadsRouteChildren = {
  AdminLeadsIdRoute: AdminLeadsIdRoute,
}

const AdminLeadsRouteWithChildren = AdminLeadsRoute._addFileChildren(
  AdminLeadsRouteChildren,
)

interface AdminPropiedadesRouteChildren {
  AdminPropiedadesNuevaRoute: typeof AdminPropiedadesNuevaRoute
  AdminPropiedadesIdEditarRoute: typeof AdminPropiedadesIdEditarRoute
}

const AdminPropiedadesRouteChildren: AdminPropiedadesRouteChildren = {
  AdminPropiedadesNuevaRoute: AdminPropiedadesNuevaRoute,
  AdminPropiedadesIdEditarRoute: AdminPropiedadesIdEditarRoute,
}

const AdminPropiedadesRouteWithChildren =
  AdminPropiedadesRoute._addFileChildren(AdminPropiedadesRouteChildren)

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLeadsRoute: typeof AdminLeadsRouteWithChildren
  AdminPropiedadesRoute: typeof AdminPropiedadesRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLeadsRoute: AdminLeadsRouteWithChildren,
  AdminPropiedadesRoute: AdminPropiedadesRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PropiedadesRouteChildren {
  PropiedadesSlugRoute: typeof PropiedadesSlugRoute
}

const PropiedadesRouteChildren: PropiedadesRouteChildren = {
  PropiedadesSlugRoute: PropiedadesSlugRoute,
}

const PropiedadesRouteWithChildren = PropiedadesRoute._addFileChildren(
  PropiedadesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactoRoute: ContactoRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  PropiedadesRoute: PropiedadesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
