/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as NosotrosRouteImport } from './routes/nosotros'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FavoritosRouteImport } from './routes/favoritos'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropiedadesIndexRouteImport } from './routes/propiedades.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as PropiedadesSlugRouteImport } from './routes/propiedades.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AdminEquipoRouteImport } from './routes/admin/equipo'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminConfiguracionRouteImport } from './routes/admin/configuracion'
import { Route as AdminAlertasRouteImport } from './routes/admin/alertas'
import { Route as AdminPropiedadesIndexRouteImport } from './routes/admin/propiedades.index'
import { Route as AdminLeadsIndexRouteImport } from './routes/admin/leads.index'
import { Route as AdminBlogIndexRouteImport } from './routes/admin/blog.index'
import { Route as AdminPropiedadesNuevaRouteImport } from './routes/admin/propiedades.nueva'
import { Route as AdminLeadsIdRouteImport } from './routes/admin/leads.$id'
import { Route as AdminBlogNuevoRouteImport } from './routes/admin/blog.nuevo'
import { Route as AdminPropiedadesIdEditarRouteImport } from './routes/admin/propiedades.$id.editar'
import { Route as AdminBlogIdEditarRouteImport } from './routes/admin/blog.$id.editar'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const NosotrosRoute = NosotrosRouteImport.update({
  id: '/nosotros',
  path: '/nosotros',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritosRoute = FavoritosRouteImport.update({
  id: '/favoritos',
  path: '/favoritos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesIndexRoute = PropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropiedadesSlugRoute = PropiedadesSlugRouteImport.update({
  id: '/propiedades/$slug',
  path: '/propiedades/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEquipoRoute = AdminEquipoRouteImport.update({
  id: '/equipo',
  path: '/equipo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracionRoute = AdminConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAlertasRoute = AdminAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropiedadesIndexRoute = AdminPropiedadesIndexRouteImport.update({
  id: '/propiedades/',
  path: '/propiedades/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIndexRoute = AdminLeadsIndexRouteImport.update({
  id: '/leads/',
  path: '/leads/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogIndexRoute = AdminBlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropiedadesNuevaRoute = AdminPropiedadesNuevaRouteImport.update({
  id: '/propiedades/nueva',
  path: '/propiedades/nueva',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsIdRoute = AdminLeadsIdRouteImport.update({
  id: '/leads/$id',
  path: '/leads/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogNuevoRoute = AdminBlogNuevoRouteImport.update({
  id: '/blog/nuevo',
  path: '/blog/nuevo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPropiedadesIdEditarRoute =
  AdminPropiedadesIdEditarRouteImport.update({
    id: '/propiedades/$id/editar',
    path: '/propiedades/$id/editar',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminBlogIdEditarRoute = AdminBlogIdEditarRouteImport.update({
  id: '/blog/$id/editar',
  path: '/blog/$id/editar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/comparar': typeof CompararRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/propiedades/': typeof AdminPropiedadesIndexRoute
  '/admin/blog/$id/editar': typeof AdminBlogIdEditarRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/comparar': typeof CompararRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/blog': typeof BlogIndexRoute
  '/propiedades': typeof PropiedadesIndexRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/blog': typeof AdminBlogIndexRoute
  '/admin/leads': typeof AdminLeadsIndexRoute
  '/admin/propiedades': typeof AdminPropiedadesIndexRoute
  '/admin/blog/$id/editar': typeof AdminBlogIdEditarRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/comparar': typeof CompararRoute
  '/contacto': typeof ContactoRoute
  '/favoritos': typeof FavoritosRoute
  '/login': typeof LoginRoute
  '/nosotros': typeof NosotrosRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/alertas': typeof AdminAlertasRoute
  '/admin/configuracion': typeof AdminConfiguracionRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/equipo': typeof AdminEquipoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/propiedades/$slug': typeof PropiedadesSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/propiedades/': typeof PropiedadesIndexRoute
  '/admin/blog/nuevo': typeof AdminBlogNuevoRoute
  '/admin/leads/$id': typeof AdminLeadsIdRoute
  '/admin/propiedades/nueva': typeof AdminPropiedadesNuevaRoute
  '/admin/blog/': typeof AdminBlogIndexRoute
  '/admin/leads/': typeof AdminLeadsIndexRoute
  '/admin/propiedades/': typeof AdminPropiedadesIndexRoute
  '/admin/blog/$id/editar': typeof AdminBlogIdEditarRoute
  '/admin/propiedades/$id/editar': typeof AdminPropiedadesIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/comparar'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/nosotros'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alertas'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/equipo'
    | '/blog/$slug'
    | '/propiedades/$slug'
    | '/blog/'
    | '/propiedades/'
    | '/admin/blog/nuevo'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/blog/'
    | '/admin/leads/'
    | '/admin/propiedades/'
    | '/admin/blog/$id/editar'
    | '/admin/propiedades/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/comparar'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/nosotros'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alertas'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/equipo'
    | '/blog/$slug'
    | '/propiedades/$slug'
    | '/blog'
    | '/propiedades'
    | '/admin/blog/nuevo'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/blog'
    | '/admin/leads'
    | '/admin/propiedades'
    | '/admin/blog/$id/editar'
    | '/admin/propiedades/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/comparar'
    | '/contacto'
    | '/favoritos'
    | '/login'
    | '/nosotros'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/alertas'
    | '/admin/configuracion'
    | '/admin/dashboard'
    | '/admin/equipo'
    | '/blog/$slug'
    | '/propiedades/$slug'
    | '/blog/'
    | '/propiedades/'
    | '/admin/blog/nuevo'
    | '/admin/leads/$id'
    | '/admin/propiedades/nueva'
    | '/admin/blog/'
    | '/admin/leads/'
    | '/admin/propiedades/'
    | '/admin/blog/$id/editar'
    | '/admin/propiedades/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CompararRoute: typeof CompararRoute
  ContactoRoute: typeof ContactoRoute
  FavoritosRoute: typeof FavoritosRoute
  LoginRoute: typeof LoginRoute
  NosotrosRoute: typeof NosotrosRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  BlogSlugRoute: typeof BlogSlugRoute
  PropiedadesSlugRoute: typeof PropiedadesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  PropiedadesIndexRoute: typeof PropiedadesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosotros': {
      id: '/nosotros'
      path: '/nosotros'
      fullPath: '/nosotros'
      preLoaderRoute: typeof NosotrosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoritos': {
      id: '/favoritos'
      path: '/favoritos'
      fullPath: '/favoritos'
      preLoaderRoute: typeof FavoritosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/': {
      id: '/propiedades/'
      path: '/propiedades'
      fullPath: '/propiedades/'
      preLoaderRoute: typeof PropiedadesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propiedades/$slug': {
      id: '/propiedades/$slug'
      path: '/propiedades/$slug'
      fullPath: '/propiedades/$slug'
      preLoaderRoute: typeof PropiedadesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/equipo': {
      id: '/admin/equipo'
      path: '/equipo'
      fullPath: '/admin/equipo'
      preLoaderRoute: typeof AdminEquipoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracion': {
      id: '/admin/configuracion'
      path: '/configuracion'
      fullPath: '/admin/configuracion'
      preLoaderRoute: typeof AdminConfiguracionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/alertas': {
      id: '/admin/alertas'
      path: '/alertas'
      fullPath: '/admin/alertas'
      preLoaderRoute: typeof AdminAlertasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propiedades/': {
      id: '/admin/propiedades/'
      path: '/propiedades'
      fullPath: '/admin/propiedades/'
      preLoaderRoute: typeof AdminPropiedadesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/': {
      id: '/admin/leads/'
      path: '/leads'
      fullPath: '/admin/leads/'
      preLoaderRoute: typeof AdminLeadsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/': {
      id: '/admin/blog/'
      path: '/blog'
      fullPath: '/admin/blog/'
      preLoaderRoute: typeof AdminBlogIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propiedades/nueva': {
      id: '/admin/propiedades/nueva'
      path: '/propiedades/nueva'
      fullPath: '/admin/propiedades/nueva'
      preLoaderRoute: typeof AdminPropiedadesNuevaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads/$id': {
      id: '/admin/leads/$id'
      path: '/leads/$id'
      fullPath: '/admin/leads/$id'
      preLoaderRoute: typeof AdminLeadsIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/nuevo': {
      id: '/admin/blog/nuevo'
      path: '/blog/nuevo'
      fullPath: '/admin/blog/nuevo'
      preLoaderRoute: typeof AdminBlogNuevoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/propiedades/$id/editar': {
      id: '/admin/propiedades/$id/editar'
      path: '/propiedades/$id/editar'
      fullPath: '/admin/propiedades/$id/editar'
      preLoaderRoute: typeof AdminPropiedadesIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog/$id/editar': {
      id: '/admin/blog/$id/editar'
      path: '/blog/$id/editar'
      fullPath: '/admin/blog/$id/editar'
      preLoaderRoute: typeof AdminBlogIdEditarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAlertasRoute: typeof AdminAlertasRoute
  AdminConfiguracionRoute: typeof AdminConfiguracionRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEquipoRoute: typeof AdminEquipoRoute
  AdminBlogNuevoRoute: typeof AdminBlogNuevoRoute
  AdminLeadsIdRoute: typeof AdminLeadsIdRoute
  AdminPropiedadesNuevaRoute: typeof AdminPropiedadesNuevaRoute
  AdminBlogIndexRoute: typeof AdminBlogIndexRoute
  AdminLeadsIndexRoute: typeof AdminLeadsIndexRoute
  AdminPropiedadesIndexRoute: typeof AdminPropiedadesIndexRoute
  AdminBlogIdEditarRoute: typeof AdminBlogIdEditarRoute
  AdminPropiedadesIdEditarRoute: typeof AdminPropiedadesIdEditarRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAlertasRoute: AdminAlertasRoute,
  AdminConfiguracionRoute: AdminConfiguracionRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEquipoRoute: AdminEquipoRoute,
  AdminBlogNuevoRoute: AdminBlogNuevoRoute,
  AdminLeadsIdRoute: AdminLeadsIdRoute,
  AdminPropiedadesNuevaRoute: AdminPropiedadesNuevaRoute,
  AdminBlogIndexRoute: AdminBlogIndexRoute,
  AdminLeadsIndexRoute: AdminLeadsIndexRoute,
  AdminPropiedadesIndexRoute: AdminPropiedadesIndexRoute,
  AdminBlogIdEditarRoute: AdminBlogIdEditarRoute,
  AdminPropiedadesIdEditarRoute: AdminPropiedadesIdEditarRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CompararRoute: CompararRoute,
  ContactoRoute: ContactoRoute,
  FavoritosRoute: FavoritosRoute,
  LoginRoute: LoginRoute,
  NosotrosRoute: NosotrosRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  BlogSlugRoute: BlogSlugRoute,
  PropiedadesSlugRoute: PropiedadesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  PropiedadesIndexRoute: PropiedadesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
